### ISSUE TITLE
当前文档主题对用户不友好

### ISSUE THREAD

**Issue by D-Sketon** [theme-shoka-x/shokaX-docs#8]
![image](https://github.com/theme-shoka-x/shokaX-docs/assets/49871906/ee98e98b-df8b-4b02-84d7-a0825e7d4581)
颜色过淡，较难看清

**Comment by zkz098** [comment]
![image](https://github.com/theme-shoka-x/shokaX-docs/assets/92242020/adb9dbd3-dd12-47a7-a887-9464b9241603)
改好了（）
